
services:
  database:
    image: postgres:15
    container_name: postgres-db-composer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: formigos1
      POSTGRES_DB: xpressdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    container_name: fastapi-api-composer
    environment:
      DB_HOST: database
      DB_NAME: xpressdb
      DB_USER: postgres
      DB_PASSWORD: formigos1
      DB_PORT: "5432"
      DATABASE_URL: postgresql://postgres:formigos1@database:5432/xpressdb
      AUTH0_DOMAIN: dev-ax53r2dultf84l0z.eu.auth0.com
      AUTH0_AUDIENCE: https://playerxpress-api.com
    depends_on:
      - database
    ports:
      - "8000:8000"


  frontend:
    build:
      context: ./app
    container_name: react-frontend-composer
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: 'http://localhost:8000'
      REACT_APP_XPRESSWAY_URL: 'http://localhost:5173'
      REACT_APP_CHATSERVICE_URL: 'http://localhost:8080'

volumes:
  postgres_data:

