
services:
  database:
    image: postgres:15
    container_name: postgres-db-composer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: formigos1
      POSTGRES_DB: xpressdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - xpressway-kong-networks

  api:
    build:
      context: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    container_name: fastapi-api-composer
    environment:
      DB_HOST: database
      DB_NAME: xpressdb
      DB_USER: postgres
      DB_PASSWORD: formigos1
      DB_PORT: "5432"
      DATABASE_URL: postgresql://postgres:formigos1@database:5432/xpressdb
      AUTH0_DOMAIN: dev-ax53r2dultf84l0z.eu.auth0.com
      AUTH0_AUDIENCE: https://playerxpress-api.com
    depends_on:
      - database
    ports:
      - "8000:8000"
    networks:
      - xpressway-kong-networks

  frontend:
    build:
      context: ./app
    container_name: react-frontend-composer
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - xpressway-kong-networks

  kong:
    image: kong:3.6
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "9000:8000" # Proxy port
      - "9443:8443" # Proxy SSL port
      - "9001:8001" # Admin API port
    depends_on:
      - api
    networks:
      - xpressway-kong-networks
volumes:
  postgres_data:

networks:
  xpressway-kong-networks:
    driver: bridge
